# Generated by Django 5.2.15 on 2026-07-08 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_organizationconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('merit', 'Merit'), ('standard_books', 'Standard Books'), ('xero', 'Xero'), ('exact', 'Exact'), ('other', 'Other')], default='merit', max_length=32)),
                ('display_name', models.CharField(max_length=255)),
                ('api_base_url', models.URLField(blank=True)),
                ('api_id', models.CharField(blank=True, max_length=255)),
                ('encrypted_secret_placeholder', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_integrations', to='core.organization')),
            ],
            options={
                'ordering': ['organization__name', 'display_name', 'id'],
            },
        ),
    ]
