# Generated by Django 5.2.15 on 2026-07-09 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0004_organizationconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('merit', 'Merit'), ('other', 'Other')], default='merit', max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('dimension_type', models.CharField(choices=[('project', 'Project'), ('department', 'Department'), ('cost_center', 'Cost center'), ('other', 'Other')], default='project', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimensions', to='accounting.accountingintegration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_dimensions', to='core.organization')),
            ],
            options={
                'ordering': ['organization__name', 'provider', 'dimension_type', 'code', 'id'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'provider', 'dimension_type', 'code'), name='unique_accounting_dimension_code'), models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('integration', 'external_id'), name='unique_accounting_dimension_external_id')],
            },
        ),
    ]
