# Generated by Django 5.2.15 on 2026-07-12 14:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountingdimension'),
        ('core', '0004_organizationconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('gl', 'General ledger'), ('sales_invoices', 'Sales invoices'), ('purchase_invoices', 'Purchase invoices'), ('payments', 'Payments'), ('accounts', 'Accounts'), ('other', 'Other')], max_length=32)),
                ('cursor_type', models.CharField(choices=[('none', 'None'), ('changed_datetime', 'Changed datetime'), ('period', 'Period'), ('external_cursor', 'External cursor'), ('other', 'Other')], default='none', max_length=32)),
                ('cursor_value', models.CharField(blank=True, default='', max_length=255)),
                ('cursor_datetime', models.DateTimeField(blank=True, null=True)),
                ('last_completed_period_start', models.DateField(blank=True, null=True)),
                ('last_completed_period_end', models.DateField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('failed', 'Failed')], default='idle', max_length=32)),
                ('initial_import_status', models.CharField(choices=[('not_started', 'Not started'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=32)),
                ('last_sync_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_progress_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('discovered_count', models.PositiveBigIntegerField(default=0)),
                ('created_count', models.PositiveBigIntegerField(default=0)),
                ('updated_count', models.PositiveBigIntegerField(default=0)),
                ('unchanged_count', models.PositiveBigIntegerField(default=0)),
                ('skipped_count', models.PositiveBigIntegerField(default=0)),
                ('failed_count', models.PositiveBigIntegerField(default=0)),
                ('cursor_metadata', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_states', to='accounting.accountingintegration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_sync_states', to='core.organization')),
            ],
            options={
                'ordering': ['organization__name', 'integration__display_name', 'source_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccountingSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('gl', 'General ledger'), ('sales_invoices', 'Sales invoices'), ('purchase_invoices', 'Purchase invoices'), ('payments', 'Payments'), ('accounts', 'Accounts'), ('other', 'Other')], max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=32)),
                ('mode', models.CharField(choices=[('incremental', 'Incremental'), ('initial_backfill', 'Initial backfill'), ('period_resync', 'Period resync'), ('manual', 'Manual'), ('other', 'Other')], default='incremental', max_length=32)),
                ('requested_period_start', models.DateField(blank=True, null=True)),
                ('requested_period_end', models.DateField(blank=True, null=True)),
                ('cursor_before', models.CharField(blank=True, default='', max_length=255)),
                ('cursor_after', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('discovered_count', models.PositiveBigIntegerField(default=0)),
                ('created_count', models.PositiveBigIntegerField(default=0)),
                ('updated_count', models.PositiveBigIntegerField(default=0)),
                ('unchanged_count', models.PositiveBigIntegerField(default=0)),
                ('skipped_count', models.PositiveBigIntegerField(default=0)),
                ('failed_count', models.PositiveBigIntegerField(default=0)),
                ('safe_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='accounting.accountingintegration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_sync_runs', to='core.organization')),
                ('sync_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='accounting.accountingsyncstate')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='accountingsyncstate',
            constraint=models.UniqueConstraint(fields=('integration', 'source_type'), name='unique_accounting_sync_state_per_source'),
        ),
    ]
