# Generated by Django 5.2.15 on 2026-07-12 15:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountingsyncstate_accountingsyncrun_and_more'),
        ('core', '0004_organizationconfiguration'),
        ('projects', '0003_projectaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingGLBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('batch_code', models.CharField(blank=True, default='', max_length=64)),
                ('number', models.CharField(blank=True, default='', max_length=64)),
                ('source_document_id', models.CharField(blank=True, default='', max_length=255)),
                ('document', models.CharField(blank=True, default='', max_length=255)),
                ('batch_date', models.DateField(blank=True, null=True)),
                ('currency_code', models.CharField(blank=True, default='', max_length=8)),
                ('currency_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('price_includes_vat', models.BooleanField(blank=True, null=True)),
                ('source_changed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('first_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_batches', to='accounting.accountingintegration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_gl_batches', to='core.organization')),
            ],
            options={
                'ordering': ['-batch_date', 'batch_code', 'number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccountingGLEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('source_entry_id', models.CharField(blank=True, default='', max_length=255)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('account_code', models.CharField(blank=True, default='', max_length=64)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('memo', models.TextField(blank=True, default='')),
                ('department_code', models.CharField(blank=True, default='', max_length=64)),
                ('debit_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('debit_currency', models.CharField(blank=True, default='', max_length=8)),
                ('credit_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('credit_currency', models.CharField(blank=True, default='', max_length=8)),
                ('type_id', models.CharField(blank=True, default='', max_length=64)),
                ('tax_id', models.CharField(blank=True, default='', max_length=64)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('first_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounting.accountingglbatch')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_entries', to='accounting.accountingintegration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_gl_entries', to='core.organization')),
            ],
            options={
                'ordering': ['batch_id', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccountingGLAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('source_type', models.CharField(blank=True, default='', max_length=64)),
                ('dimension_code', models.CharField(blank=True, default='', max_length=64)),
                ('dimension_name', models.CharField(blank=True, default='', max_length=255)),
                ('dimension_type', models.CharField(blank=True, default='', max_length=64)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('first_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_allocations', to='accounting.accountingdimension')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_allocations', to='accounting.accountingintegration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_gl_allocations', to='core.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_allocations', to='projects.project')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.accountingglentry')),
            ],
            options={
                'ordering': ['entry_id', 'dimension_code', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='accountingglbatch',
            index=models.Index(fields=['organization', 'batch_date'], name='idx_gl_batch_org_date'),
        ),
        migrations.AddIndex(
            model_name='accountingglbatch',
            index=models.Index(fields=['integration', 'source_changed_at'], name='idx_gl_batch_changed'),
        ),
        migrations.AddIndex(
            model_name='accountingglbatch',
            index=models.Index(fields=['integration', 'source_document_id'], name='idx_gl_batch_doc'),
        ),
        migrations.AddConstraint(
            model_name='accountingglbatch',
            constraint=models.UniqueConstraint(fields=('integration', 'external_id'), name='unique_gl_batch_external_id'),
        ),
        migrations.AddIndex(
            model_name='accountingglentry',
            index=models.Index(fields=['organization', 'account_code'], name='idx_gl_entry_org_account'),
        ),
        migrations.AddIndex(
            model_name='accountingglentry',
            index=models.Index(fields=['integration', 'external_id'], name='idx_gl_entry_external'),
        ),
        migrations.AddConstraint(
            model_name='accountingglentry',
            constraint=models.UniqueConstraint(fields=('integration', 'batch', 'external_id'), name='unique_gl_entry_external_id'),
        ),
        migrations.AddIndex(
            model_name='accountingglallocation',
            index=models.Index(fields=['organization', 'dimension_code'], name='idx_gl_alloc_org_dim'),
        ),
        migrations.AddIndex(
            model_name='accountingglallocation',
            index=models.Index(fields=['project'], name='idx_gl_alloc_project'),
        ),
        migrations.AddIndex(
            model_name='accountingglallocation',
            index=models.Index(fields=['integration', 'external_id'], name='idx_gl_alloc_external'),
        ),
        migrations.AddConstraint(
            model_name='accountingglallocation',
            constraint=models.UniqueConstraint(fields=('entry', 'external_id'), name='unique_gl_allocation_external_id'),
        ),
    ]
