# Generated by Django 5.2.15 on 2026-07-12 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accountingglbatch_accountingglentry_and_more'),
        ('core', '0004_organizationconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingAccountClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=64)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('revenue', 'Revenue'), ('material_cost', 'Material cost'), ('subcontractor_cost', 'Subcontractor cost'), ('labor_cost', 'Labor cost'), ('equipment_cost', 'Equipment cost'), ('transport_cost', 'Transport cost'), ('other_direct_cost', 'Other direct cost'), ('overhead', 'Overhead'), ('financial_income', 'Financial income'), ('financial_cost', 'Financial cost'), ('depreciation', 'Depreciation'), ('tax', 'Tax'), ('excluded', 'Excluded'), ('unclassified', 'Unclassified')], default='unclassified', max_length=32)),
                ('reporting_sign', models.DecimalField(decimal_places=0, default=1, max_digits=2)),
                ('include_in_project_result', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_classifications', to='accounting.accountingintegration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_account_classifications', to='core.organization')),
            ],
            options={
                'ordering': ['organization__name', 'integration__display_name', 'account_code', 'id'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'integration', 'account_code'), name='unique_account_classification_integration_code'), models.UniqueConstraint(condition=models.Q(('integration__isnull', True)), fields=('organization', 'account_code'), name='unique_account_classification_org_fallback_code')],
            },
        ),
    ]
