# Generated by Django 5.2.15 on 2026-07-13 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_accountingaccountclassification'),
        ('core', '0004_organizationconfiguration'),
        ('projects', '0003_projectaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementAllocationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_allocation_periods', to='core.organization')),
            ],
            options={
                'ordering': ['organization__name', '-year', '-month', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManagementAllocationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('superseded', 'Superseded')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_management_allocation_versions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_management_allocation_versions', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='accounting.managementallocationperiod')),
            ],
            options={
                'ordering': ['period', 'pool__display_order', 'pool__name', '-version_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManagementAllocationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('manual_override', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_allocation_entries', to='projects.project')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounting.managementallocationversion')),
            ],
            options={
                'ordering': ['version', 'project__code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManagementCostPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('default_strategy', models.CharField(choices=[('revenue', 'Revenue'), ('equal', 'Equal'), ('manual_percent', 'Manual percent'), ('manual_amount', 'Manual amount'), ('project_manager', 'Project manager')], default='revenue', max_length=32)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_cost_pools', to='core.organization')),
            ],
            options={
                'ordering': ['organization__name', 'display_order', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='managementallocationversion',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_versions', to='accounting.managementcostpool'),
        ),
        migrations.CreateModel(
            name='ManagementAllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('revenue', 'Revenue'), ('equal', 'Equal'), ('manual_percent', 'Manual percent'), ('manual_amount', 'Manual amount'), ('project_manager', 'Project manager')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_rules', to='accounting.managementcostpool')),
            ],
            options={
                'ordering': ['pool__organization__name', 'pool__display_order', 'pool__name', 'strategy', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManagementCostPoolAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.managementcostpool')),
            ],
            options={
                'ordering': ['pool__organization__name', 'pool__name', 'account_code', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='managementallocationperiod',
            constraint=models.UniqueConstraint(fields=('organization', 'year', 'month'), name='unique_management_period'),
        ),
        migrations.AddConstraint(
            model_name='managementcostpool',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_management_cost_pool_name'),
        ),
        migrations.AddConstraint(
            model_name='managementallocationversion',
            constraint=models.UniqueConstraint(fields=('period', 'pool', 'version_number'), name='unique_management_version_number'),
        ),
        migrations.AddConstraint(
            model_name='managementallocationversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('period', 'pool'), name='unique_approved_management_version'),
        ),
        migrations.AddConstraint(
            model_name='managementcostpoolaccount',
            constraint=models.UniqueConstraint(fields=('pool', 'account_code'), name='unique_management_pool_account_code'),
        ),
    ]
