# Generated by Django 5.2.15 on 2026-07-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_managementallocationperiod_and_more'),
        ('projects', '0003_projectaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementallocationversion',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='managementallocationentry',
            constraint=models.UniqueConstraint(fields=('version', 'project'), name='unique_management_entry_project'),
        ),
    ]
