# Generated by Django 5.2.16 on 2026-07-13 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_managementallocationversion_metadata_and_more'),
        ('projects', '0003_projectaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managementallocationversion',
            options={'ordering': ['period', 'source_type', 'pool__display_order', 'pool__name', 'source_project__code', '-version_number', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='managementallocationversion',
            name='unique_management_version_number',
        ),
        migrations.RemoveConstraint(
            model_name='managementallocationversion',
            name='unique_approved_management_version',
        ),
        migrations.AddField(
            model_name='managementallocationversion',
            name='source_amount_basis',
            field=models.CharField(choices=[('mapped_gl_accounts', 'Mapped GL accounts'), ('project_direct_cost', 'Project direct cost'), ('project_selected_costs', 'Project selected costs'), ('manual', 'Manual')], default='mapped_gl_accounts', max_length=32),
        ),
        migrations.AddField(
            model_name='managementallocationversion',
            name='source_currency',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='managementallocationversion',
            name='source_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementallocationversion',
            name='source_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementallocationversion',
            name='source_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourced_management_allocation_versions', to='projects.project'),
        ),
        migrations.AddField(
            model_name='managementallocationversion',
            name='source_type',
            field=models.CharField(choices=[('cost_pool', 'Cost pool'), ('workspace_project', 'Workspace Project')], default='cost_pool', max_length=32),
        ),
        migrations.AlterField(
            model_name='managementallocationversion',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocation_versions', to='accounting.managementcostpool'),
        ),
        migrations.AddConstraint(
            model_name='managementallocationversion',
            constraint=models.UniqueConstraint(condition=models.Q(('pool__isnull', False)), fields=('period', 'pool', 'version_number'), name='unique_management_pool_version_number'),
        ),
        migrations.AddConstraint(
            model_name='managementallocationversion',
            constraint=models.UniqueConstraint(condition=models.Q(('source_project__isnull', False)), fields=('period', 'source_project', 'version_number'), name='unique_management_project_version_number'),
        ),
        migrations.AddConstraint(
            model_name='managementallocationversion',
            constraint=models.UniqueConstraint(condition=models.Q(('pool__isnull', False), ('status', 'approved')), fields=('period', 'pool'), name='unique_approved_management_pool_version'),
        ),
        migrations.AddConstraint(
            model_name='managementallocationversion',
            constraint=models.UniqueConstraint(condition=models.Q(('source_project__isnull', False), ('status', 'approved')), fields=('period', 'source_project'), name='unique_approved_management_project_version'),
        ),
        migrations.AddConstraint(
            model_name='managementallocationversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pool__isnull', False), ('source_project__isnull', True), ('source_type', 'cost_pool')), models.Q(('pool__isnull', True), ('source_project__isnull', False), ('source_type', 'workspace_project')), _connector='OR'), name='management_allocation_valid_source'),
        ),
    ]
