# Generated by Django 5.2.16 on 2026-07-14 08:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_managementallocationversion_options_and_more'),
        ('core', '0004_organizationconfiguration'),
        ('projects', '0003_projectaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAlertEvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=32)),
                ('evaluation_date', models.DateField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_project_count', models.PositiveIntegerField(default=0)),
                ('evaluated_project_count', models.PositiveIntegerField(default=0)),
                ('evaluated_rule_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('reopened_count', models.PositiveIntegerField(default=0)),
                ('resolved_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('safe_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_alert_evaluation_runs', to='core.organization')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('project_lifetime_negative', 'Project lifetime negative'), ('project_current_month_negative', 'Project current-month negative'), ('project_current_month_no_revenue', 'Project current-month no revenue')], max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('financial_basis', models.CharField(choices=[('accounting', 'Accounting'), ('management', 'Management')], default='management', max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=32)),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('threshold_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('grace_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('project_status_scope', models.JSONField(blank=True, default=list)),
                ('candidate_scope', models.CharField(choices=[('active_projects', 'Active projects'), ('active_projects_with_month_activity', 'Active projects with month activity'), ('all_with_activity', 'All with activity'), ('selected_projects', 'Selected projects')], default='active_projects', max_length=64)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_alert_rules', to='core.organization')),
            ],
            options={
                'ordering': ['organization__name', 'alert_type', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('project_lifetime_negative', 'Project lifetime negative'), ('project_current_month_negative', 'Project current-month negative'), ('project_current_month_no_revenue', 'Project current-month no revenue')], max_length=64)),
                ('financial_basis', models.CharField(choices=[('accounting', 'Accounting'), ('management', 'Management')], max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=32)),
                ('fingerprint', models.CharField(max_length=64)),
                ('fingerprint_version', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('accounting_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('management_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('evaluated_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('data_quality_status', models.CharField(blank=True, default='', max_length=64)),
                ('first_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_financial_alerts', to=settings.AUTH_USER_MODEL)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_financial_alerts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_alerts', to='core.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_alerts', to='projects.project')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='accounting.financialalertrule')),
            ],
            options={
                'ordering': ['-last_detected_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='financialalertrule',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_financial_alert_rule_name'),
        ),
        migrations.AddConstraint(
            model_name='financialalertrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization', 'alert_type'), name='unique_active_financial_alert_rule_type'),
        ),
        migrations.AddConstraint(
            model_name='financialalertrule',
            constraint=models.CheckConstraint(condition=models.Q(('grace_day__isnull', True), models.Q(('grace_day__gte', 1), ('grace_day__lte', 31)), _connector='OR'), name='financial_alert_rule_grace_day_range'),
        ),
        migrations.AddIndex(
            model_name='financialalert',
            index=models.Index(fields=['organization', 'status'], name='idx_fin_alert_org_status'),
        ),
        migrations.AddIndex(
            model_name='financialalert',
            index=models.Index(fields=['project', 'status'], name='idx_fin_alert_project_status'),
        ),
        migrations.AddIndex(
            model_name='financialalert',
            index=models.Index(fields=['alert_type', 'status'], name='idx_fin_alert_type_status'),
        ),
        migrations.AddIndex(
            model_name='financialalert',
            index=models.Index(fields=['period_start', 'period_end'], name='idx_fin_alert_period'),
        ),
        migrations.AddIndex(
            model_name='financialalert',
            index=models.Index(fields=['severity', 'status'], name='idx_fin_alert_severity_status'),
        ),
        migrations.AddIndex(
            model_name='financialalert',
            index=models.Index(fields=['last_detected_at'], name='idx_fin_alert_last_detected'),
        ),
        migrations.AddConstraint(
            model_name='financialalert',
            constraint=models.UniqueConstraint(fields=('organization', 'fingerprint'), name='unique_financial_alert_fingerprint'),
        ),
    ]
