# Generated by Django 5.2.16 on 2026-07-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_financialalertevaluationrun_financialalertrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialalert',
            name='alert_type',
            field=models.CharField(choices=[('project_lifetime_negative', 'Project lifetime negative'), ('project_current_month_negative', 'Project current-month negative'), ('project_current_month_no_revenue', 'Project current-month no revenue'), ('project_margin_below_threshold', 'Project margin below threshold')], max_length=64),
        ),
        migrations.AlterField(
            model_name='financialalertrule',
            name='alert_type',
            field=models.CharField(choices=[('project_lifetime_negative', 'Project lifetime negative'), ('project_current_month_negative', 'Project current-month negative'), ('project_current_month_no_revenue', 'Project current-month no revenue'), ('project_margin_below_threshold', 'Project margin below threshold')], max_length=64),
        ),
    ]
