# Generated by Django 5.2.15 on 2026-06-30 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_organizationconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='active', max_length=32)),
                ('project_type', models.CharField(choices=[('construction', 'Construction'), ('electrical', 'Electrical'), ('service', 'Service'), ('internal', 'Internal'), ('sales', 'Sales'), ('other', 'Other')], default='other', max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.organization')),
            ],
            options={
                'ordering': ['organization__name', 'code', 'id'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='unique_project_code_per_organization')],
            },
        ),
    ]
