# Generated by Django 5.2.15 on 2026-06-30 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organizationconfiguration'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('subcontractor', 'Subcontractor'), ('project_manager', 'Project manager'), ('site_manager', 'Site manager'), ('electrician', 'Electrician'), ('designer', 'Designer'), ('architect', 'Architect'), ('owner_supervisor', 'Owner supervisor'), ('authority', 'Authority'), ('accountant', 'Accountant'), ('other', 'Other')], default='other', max_length=32)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_parties', to='core.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='projects.project')),
            ],
            options={
                'ordering': ['project__code', 'role', 'name', 'id'],
            },
        ),
    ]
