# Generated by Django 5.2.15 on 2026-06-30 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organizationconfiguration'),
        ('projects', '0002_projectparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('site', 'Site'), ('billing', 'Billing'), ('postal', 'Postal'), ('warehouse', 'Warehouse'), ('temporary', 'Temporary'), ('other', 'Other')], default='site', max_length=32)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(default='EE', max_length=2)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_addresses', to='core.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='projects.project')),
            ],
            options={
                'ordering': ['project__code', 'address_type', 'id'],
            },
        ),
    ]
