from django.urls import path

from .views import (
    AccountingIntegrationCreateView,
    AccountingIntegrationDetailView,
    AccountingIntegrationEditView,
    AccountingIntegrationListView,
    AccountingIntegrationTestConnectionView,
    AccountClassificationDetailView,
    AccountClassificationEditView,
    AccountClassificationListView,
    AccountingDimensionConflictsView,
    AssistantView,
    CommunicationCandidatesView,
    CommunicationCandidateDetailView,
    CommunicationCandidateReviewPostView,
    CommunicationProjectLinksView,
    DashboardView,
    DesignSystemView,
    DocumentsView,
    EmailDraftApproveView,
    EmailDraftCreateView,
    EmailDraftNeedsReviewView,
    EmailDraftRejectView,
    EmailAccountCreateView,
    EmailAccountDetailView,
    EmailAccountEditView,
    EmailAccountListView,
    EmailAccountTestConnectionView,
    FinancialDashboardView,
    FinancialDashboardSyncMonthView,
    FinancialAlertAcknowledgeView,
    FinancialAlertDetailView,
    FinancialAlertDismissView,
    FinancialAlertRuleEditView,
    FinancialAlertRuleListView,
    FinancialAlertRuleReevaluateView,
    FinancialAlertsView,
    InboxDetailView,
    InboxSyncView,
    ManagementAllocationApproveView,
    ManagementAllocationCreateView,
    ManagementAllocationDetailView,
    ManagementAllocationEditView,
    ManagementAllocationListView,
    ManagementAllocationSourcePreviewView,
    ManagementAllocationReviseView,
    MeritDimensionSyncView,
    InboxView,
    ProjectCreateView,
    ProjectCreateFromDimensionView,
    ProjectDetailView,
    ProjectEditView,
    ProjectFinancialAllocationsView,
    ProjectFinancialsView,
    ProjectAlertsView,
    ProjectLinkConfirmView,
    ProjectLinkCorrectView,
    ProjectLinkRejectView,
    ProjectStatusView,
    ProjectsView,
    ReviewsView,
    SearchView,
    SettingsSectionView,
    SettingsView,
)

app_name = "workspace"

urlpatterns = [
    path("", DashboardView.as_view(), name="home"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("inbox/", InboxView.as_view(), name="inbox"),
    path("inbox/sync/", InboxSyncView.as_view(), name="inbox_sync"),
    path("inbox/<int:email_id>/", InboxDetailView.as_view(), name="inbox_detail"),
    path("inbox/<int:email_id>/drafts/create/", EmailDraftCreateView.as_view(), name="email_draft_create"),
    path("drafts/<int:draft_id>/needs-review/", EmailDraftNeedsReviewView.as_view(), name="draft_needs_review"),
    path("drafts/<int:draft_id>/approve/", EmailDraftApproveView.as_view(), name="draft_approve"),
    path("drafts/<int:draft_id>/reject/", EmailDraftRejectView.as_view(), name="draft_reject"),
    path("project-links/<int:link_id>/confirm/", ProjectLinkConfirmView.as_view(), name="project_link_confirm"),
    path("project-links/<int:link_id>/reject/", ProjectLinkRejectView.as_view(), name="project_link_reject"),
    path("project-links/<int:link_id>/correct/", ProjectLinkCorrectView.as_view(), name="project_link_correct"),
    path("projects/", ProjectsView.as_view(), name="projects"),
    path("projects/create/", ProjectCreateView.as_view(), name="project_create"),
    path(
        "projects/from-dimension/<int:dimension_id>/create/",
        ProjectCreateFromDimensionView.as_view(),
        name="project_create_from_dimension",
    ),
    path("projects/<int:project_id>/edit/", ProjectEditView.as_view(), name="project_edit"),
    path("projects/<int:project_id>/status/", ProjectStatusView.as_view(), name="project_status"),
    path("projects/<int:project_id>/financials/", ProjectFinancialsView.as_view(), name="project_financials"),
    path("projects/<int:project_id>/alerts/", ProjectAlertsView.as_view(), name="project_alerts"),
    path(
        "projects/<int:project_id>/financials/allocations/",
        ProjectFinancialAllocationsView.as_view(),
        name="project_financial_allocations",
    ),
    path("projects/<int:project_id>/", ProjectDetailView.as_view(), name="project_detail"),
    path("financials/", FinancialDashboardView.as_view(), name="financial_dashboard"),
    path("financials/sync-month/", FinancialDashboardSyncMonthView.as_view(), name="financial_dashboard_sync_month"),
    path("alerts/", FinancialAlertsView.as_view(), name="financial_alerts"),
    path("alerts/<int:alert_id>/", FinancialAlertDetailView.as_view(), name="financial_alert_detail"),
    path("alerts/<int:alert_id>/acknowledge/", FinancialAlertAcknowledgeView.as_view(), name="financial_alert_acknowledge"),
    path("alerts/<int:alert_id>/dismiss/", FinancialAlertDismissView.as_view(), name="financial_alert_dismiss"),
    path("management-allocations/", ManagementAllocationListView.as_view(), name="management_allocations"),
    path("management-allocations/create/", ManagementAllocationCreateView.as_view(), name="management_allocation_create"),
    path(
        "management-allocations/source-preview/",
        ManagementAllocationSourcePreviewView.as_view(),
        name="management_allocation_source_preview",
    ),
    path(
        "management-allocations/<int:version_id>/",
        ManagementAllocationDetailView.as_view(),
        name="management_allocation_detail",
    ),
    path(
        "management-allocations/<int:version_id>/edit/",
        ManagementAllocationEditView.as_view(),
        name="management_allocation_edit",
    ),
    path(
        "management-allocations/<int:version_id>/approve/",
        ManagementAllocationApproveView.as_view(),
        name="management_allocation_approve",
    ),
    path(
        "management-allocations/<int:version_id>/revise/",
        ManagementAllocationReviseView.as_view(),
        name="management_allocation_revise",
    ),
    path("accounting/dimensions/sync/", MeritDimensionSyncView.as_view(), name="merit_dimensions_sync"),
    path(
        "accounting/dimensions/conflicts/",
        AccountingDimensionConflictsView.as_view(),
        name="accounting_dimension_conflicts",
    ),
    path("documents/", DocumentsView.as_view(), name="documents"),
    path("reviews/", ReviewsView.as_view(), name="reviews"),
    path("ai-review/", CommunicationCandidatesView.as_view(), name="communication_ai_review"),
    path(
        "ai-review/<int:candidate_id>/",
        CommunicationCandidateDetailView.as_view(),
        name="communication_candidate_review",
    ),
    path(
        "ai-review/<int:candidate_id>/review/",
        CommunicationCandidateReviewPostView.as_view(),
        name="communication_candidate_review_post",
    ),
    path(
        "communications/project-links/",
        CommunicationProjectLinksView.as_view(),
        name="communication_project_links",
    ),
    path(
        "communications/candidates/",
        CommunicationCandidatesView.as_view(),
        name="communication_candidates",
    ),
    path("search/", SearchView.as_view(), name="search"),
    path("assistant/", AssistantView.as_view(), name="assistant"),
    path("settings/", SettingsView.as_view(), name="settings"),
    path(
        "settings/financial-alert-rules/",
        FinancialAlertRuleListView.as_view(),
        name="settings_financial_alert_rules",
    ),
    path(
        "settings/financial-alert-rules/evaluate/",
        FinancialAlertRuleReevaluateView.as_view(),
        name="settings_financial_alert_rules_evaluate",
    ),
    path(
        "settings/financial-alert-rules/<int:rule_id>/edit/",
        FinancialAlertRuleEditView.as_view(),
        name="settings_financial_alert_rule_edit",
    ),
    path("settings/email-accounts/", EmailAccountListView.as_view(), name="settings_email_accounts"),
    path("settings/email-accounts/create/", EmailAccountCreateView.as_view(), name="settings_email_account_create"),
    path("settings/email-accounts/<int:account_id>/", EmailAccountDetailView.as_view(), name="settings_email_account_detail"),
    path("settings/email-accounts/<int:account_id>/edit/", EmailAccountEditView.as_view(), name="settings_email_account_edit"),
    path(
        "settings/email-accounts/<int:account_id>/test-connection/",
        EmailAccountTestConnectionView.as_view(),
        name="settings_email_account_test_connection",
    ),
    path(
        "settings/accounting-integrations/",
        AccountingIntegrationListView.as_view(),
        name="settings_accounting_integrations",
    ),
    path(
        "settings/accounting-integrations/create/",
        AccountingIntegrationCreateView.as_view(),
        name="settings_accounting_integration_create",
    ),
    path(
        "settings/accounting-integrations/<int:integration_id>/",
        AccountingIntegrationDetailView.as_view(),
        name="settings_accounting_integration_detail",
    ),
    path(
        "settings/accounting-integrations/<int:integration_id>/edit/",
        AccountingIntegrationEditView.as_view(),
        name="settings_accounting_integration_edit",
    ),
    path(
        "settings/accounting-integrations/<int:integration_id>/test-connection/",
        AccountingIntegrationTestConnectionView.as_view(),
        name="settings_accounting_integration_test_connection",
    ),
    path(
        "settings/account-classifications/",
        AccountClassificationListView.as_view(),
        name="settings_account_classifications",
    ),
    path(
        "settings/account-classifications/<str:account_code>/edit/",
        AccountClassificationEditView.as_view(),
        name="settings_account_classification_edit",
    ),
    path(
        "settings/account-classifications/<str:account_code>/",
        AccountClassificationDetailView.as_view(),
        name="settings_account_classification_detail",
    ),
    path("settings/<slug:section_slug>/", SettingsSectionView.as_view(), name="settings_section"),
    path("design-system/", DesignSystemView.as_view(), name="design_system"),
]
