from django.urls import path

from .views import (
    AssistantView,
    DashboardView,
    DesignSystemView,
    DocumentsView,
    EmailDraftApproveView,
    EmailDraftCreateView,
    EmailDraftNeedsReviewView,
    EmailDraftRejectView,
    InboxDetailView,
    InboxSyncView,
    MeritDimensionSyncView,
    InboxView,
    ProjectCreateView,
    ProjectDetailView,
    ProjectLinkConfirmView,
    ProjectLinkCorrectView,
    ProjectLinkRejectView,
    ProjectsView,
    ReviewsView,
    SearchView,
    SettingsSectionView,
    SettingsView,
)

app_name = "workspace"

urlpatterns = [
    path("", DashboardView.as_view(), name="home"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("inbox/", InboxView.as_view(), name="inbox"),
    path("inbox/sync/", InboxSyncView.as_view(), name="inbox_sync"),
    path("inbox/<int:email_id>/", InboxDetailView.as_view(), name="inbox_detail"),
    path("inbox/<int:email_id>/drafts/create/", EmailDraftCreateView.as_view(), name="email_draft_create"),
    path("drafts/<int:draft_id>/needs-review/", EmailDraftNeedsReviewView.as_view(), name="draft_needs_review"),
    path("drafts/<int:draft_id>/approve/", EmailDraftApproveView.as_view(), name="draft_approve"),
    path("drafts/<int:draft_id>/reject/", EmailDraftRejectView.as_view(), name="draft_reject"),
    path("project-links/<int:link_id>/confirm/", ProjectLinkConfirmView.as_view(), name="project_link_confirm"),
    path("project-links/<int:link_id>/reject/", ProjectLinkRejectView.as_view(), name="project_link_reject"),
    path("project-links/<int:link_id>/correct/", ProjectLinkCorrectView.as_view(), name="project_link_correct"),
    path("projects/", ProjectsView.as_view(), name="projects"),
    path("projects/create/", ProjectCreateView.as_view(), name="project_create"),
    path("projects/<int:project_id>/", ProjectDetailView.as_view(), name="project_detail"),
    path("accounting/dimensions/sync/", MeritDimensionSyncView.as_view(), name="merit_dimensions_sync"),
    path("documents/", DocumentsView.as_view(), name="documents"),
    path("reviews/", ReviewsView.as_view(), name="reviews"),
    path("search/", SearchView.as_view(), name="search"),
    path("assistant/", AssistantView.as_view(), name="assistant"),
    path("settings/", SettingsView.as_view(), name="settings"),
    path("settings/<slug:section_slug>/", SettingsSectionView.as_view(), name="settings_section"),
    path("design-system/", DesignSystemView.as_view(), name="design_system"),
]
