# Generated by Django 5.2.15 on 2026-06-30 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_organizationconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('imap', 'IMAP'), ('microsoft_365', 'Microsoft 365'), ('pst_import', 'PST import'), ('gmail', 'Gmail'), ('other', 'Other')], max_length=32)),
                ('display_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('use_ssl', models.BooleanField(default=True)),
                ('use_tls', models.BooleanField(default=False)),
                ('auth_type', models.CharField(blank=True, max_length=64)),
                ('encrypted_secret_placeholder', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to='core.organization')),
            ],
            options={
                'ordering': ['organization__name', 'display_name', 'id'],
            },
        ),
    ]
