# Generated by Django 5.2.15 on 2026-06-30 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_emailattachment'),
        ('core', '0004_organizationconfiguration'),
        ('projects', '0003_projectaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('corrected', 'Corrected')], default='suggested', max_length=32)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_email_project_links', to=settings.AUTH_USER_MODEL)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='communications.emailmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_project_links', to='core.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_links', to='projects.project')),
            ],
            options={
                'ordering': ['email_message_id', 'project__code', 'id'],
                'constraints': [models.UniqueConstraint(fields=('email_message', 'project'), name='unique_email_project_link')],
            },
        ),
    ]
