# Generated by Django 5.2.15 on 2026-06-30 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_emailprojectlink'),
        ('core', '0004_organizationconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('detection_method', models.CharField(choices=[('rule_based', 'Rule based'), ('ai', 'AI'), ('manual', 'Manual')], default='rule_based', max_length=32)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('answered', 'Answered')], default='detected', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='communications.emailmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_questions', to='core.organization')),
            ],
            options={
                'ordering': ['email_message_id', '-confidence', 'id'],
            },
        ),
    ]
