# Generated by Django 5.2.15 on 2026-07-07 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_emailquestion'),
        ('core', '0004_organizationconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAnswerDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Sent')], default='draft', max_length=32)),
                ('draft_text', models.TextField(blank=True)),
                ('final_text', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.CharField(choices=[('rule_based', 'Rule based'), ('ai', 'AI'), ('manual', 'Manual')], default='rule_based', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_email_answer_drafts', to=settings.AUTH_USER_MODEL)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_drafts', to='communications.emailmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_answer_drafts', to='core.organization')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_drafts', to='communications.emailquestion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_email_answer_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
