# Generated by Django 5.2.15 on 2026-07-12 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_emailanswerdraft'),
        ('core', '0004_organizationconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMailboxState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox_name', models.CharField(max_length=255)),
                ('external_mailbox_id', models.CharField(blank=True, default='', max_length=255)),
                ('uid_validity', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_discovered_uid', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_processed_uid', models.PositiveBigIntegerField(blank=True, null=True)),
                ('highest_modseq', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('failed', 'Failed')], default='idle', max_length=32)),
                ('initial_import_status', models.CharField(choices=[('not_started', 'Not started'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=32)),
                ('last_sync_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_progress_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('discovered_count', models.PositiveBigIntegerField(default=0)),
                ('imported_count', models.PositiveBigIntegerField(default=0)),
                ('processed_count', models.PositiveBigIntegerField(default=0)),
                ('skipped_count', models.PositiveBigIntegerField(default=0)),
                ('failed_count', models.PositiveBigIntegerField(default=0)),
                ('cursor_metadata', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_states', to='communications.emailaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_mailbox_states', to='core.organization')),
            ],
            options={
                'ordering': ['email_account__email_address', 'mailbox_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('email_account', 'mailbox_name'), name='unique_mailbox_state_per_account')],
            },
        ),
    ]
