# Generated by Django 5.2.16 on 2026-07-14 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_emailmailboxstate'),
        ('core', '0004_organizationconfiguration'),
        ('projects', '0003_projectaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailprojectlink',
            name='confidence_band',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='emailprojectlink',
            name='evidence_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='emailprojectlink',
            name='evidence_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailprojectlink',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailprojectlink',
            name='last_evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailprojectlink',
            name='rule_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='emailprojectlink',
            name='source',
            field=models.CharField(blank=True, choices=[('exact_project_code_subject', 'Exact project code in subject'), ('exact_project_code_body', 'Exact project code in body'), ('confirmed_thread_link', 'Confirmed thread link'), ('explicit_user_link', 'Explicit user link'), ('existing_legacy_link', 'Existing legacy link'), ('attachment_document_link', 'Attachment document link'), ('project_alias', 'Project alias'), ('participant_plus_evidence', 'Participant plus evidence'), ('imported_backfill', 'Imported backfill')], default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='emailprojectlink',
            index=models.Index(fields=['organization', 'status'], name='email_project_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='emailprojectlink',
            index=models.Index(fields=['project', 'status'], name='email_project_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='emailprojectlink',
            index=models.Index(fields=['email_message', 'status'], name='email_project_msg_status_idx'),
        ),
        migrations.AddIndex(
            model_name='emailprojectlink',
            index=models.Index(fields=['source', 'status'], name='email_project_src_status_idx'),
        ),
        migrations.AddIndex(
            model_name='emailprojectlink',
            index=models.Index(fields=['confidence_band'], name='email_project_conf_band_idx'),
        ),
        migrations.AddIndex(
            model_name='emailprojectlink',
            index=models.Index(fields=['last_evaluated_at'], name='email_project_eval_idx'),
        ),
    ]
