# Generated by Django 5.2.16 on 2026-07-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_emailprojectlink_confidence_band_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailprojectlink',
            name='status',
            field=models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('corrected', 'Corrected'), ('superseded', 'Superseded')], default='suggested', max_length=32),
        ),
    ]
