# Generated by Django 5.2.16 on 2026-07-14 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_alter_emailprojectlink_status'),
        ('core', '0004_organizationconfiguration'),
        ('projects', '0003_projectaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationIntelligenceCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_type', models.CharField(choices=[('question', 'Question'), ('task_request', 'Task request'), ('commitment', 'Commitment'), ('decision', 'Decision'), ('risk', 'Risk'), ('blocker', 'Blocker'), ('deadline', 'Deadline'), ('information_only', 'Information only'), ('resolution_evidence', 'Resolution evidence')], max_length=32)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('edited_and_approved', 'Edited and approved'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('merged', 'Merged'), ('expired', 'Expired')], default='pending_review', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence_band', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16)),
                ('extraction_method', models.CharField(choices=[('deterministic_rule', 'Deterministic rule'), ('language_model', 'Language model'), ('hybrid', 'Hybrid')], default='deterministic_rule', max_length=32)),
                ('suggested_responsible_party', models.CharField(blank=True, max_length=255)),
                ('suggested_responsible_email', models.EmailField(blank=True, max_length=254)),
                ('suggested_due_date', models.DateField(blank=True, null=True)),
                ('suggested_priority', models.CharField(blank=True, max_length=32)),
                ('source_evidence_summary', models.TextField(blank=True)),
                ('evidence_excerpt', models.TextField(blank=True)),
                ('evidence_fingerprint', models.CharField(max_length=64)),
                ('content_fingerprint', models.CharField(max_length=64)),
                ('extractor_version', models.CharField(max_length=64)),
                ('model_provider', models.CharField(blank=True, max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('prompt_version', models.CharField(blank=True, max_length=64)),
                ('rule_version', models.CharField(blank=True, max_length=64)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_candidates', to='communications.emailmessage')),
                ('email_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_candidates', to='communications.emailthread')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_candidates', to='communications.communicationintelligencecandidate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_intelligence_candidates', to='core.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_candidates', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_communication_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'status'], name='comm_cand_org_status_idx'), models.Index(fields=['project', 'status'], name='comm_cand_proj_status_idx'), models.Index(fields=['candidate_type', 'status'], name='comm_cand_type_status_idx'), models.Index(fields=['email_message', 'status'], name='comm_cand_msg_status_idx'), models.Index(fields=['confidence_band', 'status'], name='comm_cand_conf_status_idx'), models.Index(fields=['created_at'], name='comm_cand_created_idx'), models.Index(fields=['suggested_due_date'], name='comm_cand_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'email_message', 'project', 'candidate_type', 'evidence_fingerprint'), name='unique_communication_candidate_evidence')],
            },
        ),
    ]
