# Generated by Django 5.2.16 on 2026-07-15 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_communicationintelligencecandidate'),
        ('projects', '0003_projectaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationintelligencecandidate',
            name='human_feedback',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='communicationintelligencecandidate',
            name='review_outcome',
            field=models.CharField(blank=True, choices=[('approve', 'Approve'), ('edit_and_approve', 'Edit and approve'), ('reject', 'Reject'), ('not_actionable', 'Not actionable'), ('duplicate', 'Duplicate'), ('merge', 'Merge'), ('defer', 'Defer')], max_length=32),
        ),
        migrations.AddField(
            model_name='communicationintelligencecandidate',
            name='review_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='communicationintelligencecandidate',
            name='review_snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationintelligencecandidate',
            name='review_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='communicationintelligencecandidate',
            name='reviewed_candidate_type',
            field=models.CharField(blank=True, choices=[('question', 'Question'), ('task_request', 'Task request'), ('commitment', 'Commitment'), ('decision', 'Decision'), ('risk', 'Risk'), ('blocker', 'Blocker'), ('deadline', 'Deadline'), ('information_only', 'Information only'), ('resolution_evidence', 'Resolution evidence')], max_length=32),
        ),
        migrations.AddField(
            model_name='communicationintelligencecandidate',
            name='reviewed_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='communicationintelligencecandidate',
            name='reviewed_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationintelligencecandidate',
            name='reviewed_due_date_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communicationintelligencecandidate',
            name='reviewed_priority',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='communicationintelligencecandidate',
            name='reviewed_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_communication_candidates', to='projects.project'),
        ),
        migrations.AddField(
            model_name='communicationintelligencecandidate',
            name='reviewed_responsible_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='communicationintelligencecandidate',
            name='reviewed_responsible_party',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='communicationintelligencecandidate',
            name='reviewed_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
