# Generated by Django 5.2.15 on 2026-06-28 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_workflowinstance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('workflow_started', 'Workflow started'), ('state_entered', 'State entered'), ('state_exited', 'State exited'), ('transition_executed', 'Transition executed'), ('manual_override', 'Manual override'), ('policy_denied', 'Policy denied'), ('policy_approved', 'Policy approved'), ('retry', 'Retry'), ('timeout', 'Timeout'), ('workflow_completed', 'Workflow completed'), ('workflow_cancelled', 'Workflow cancelled')], max_length=64)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_events', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_events', to='workflow.workflowstate')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_events', to='workflow.workflowtransition')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workflow.workflowinstance')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
