# Generated by Django 5.2.15 on 2026-06-27 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('mail', 'Mail'), ('manual_upload', 'Manual upload'), ('bank_import', 'Bank import'), ('merit_import', 'Merit import'), ('emta_export', 'EMTA export'), ('api', 'API'), ('other', 'Other')], default='other', max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('parsed', 'Parsed'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('archived', 'Archived'), ('error', 'Error')], default='new', max_length=32)),
                ('file', models.FileField(blank=True, upload_to='documents/originals/%Y/%m/')),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='documents.document')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('document', 'name'), name='unique_document_tag_name')],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(blank=True, upload_to='documents/versions/%Y/%m/')),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'ordering': ['document_id', 'version_number'],
                'constraints': [models.UniqueConstraint(fields=('document', 'version_number'), name='unique_document_version_number')],
            },
        ),
    ]
