# Generated by Django 5.2.15 on 2026-06-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('mail', 'Mail'), ('email_attachment', 'Email attachment'), ('manual_upload', 'Manual upload'), ('bank_import', 'Bank import'), ('merit_import', 'Merit import'), ('emta_export', 'EMTA export'), ('api', 'API'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
