# Generated by Django 5.2.15 on 2026-06-28 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('organization_type', models.CharField(choices=[('company', 'Company'), ('sole_proprietor', 'Sole proprietor'), ('non_profit', 'Non-profit'), ('government', 'Government'), ('other', 'Other')], default='company', max_length=32)),
                ('registration_number', models.CharField(blank=True, max_length=64)),
                ('vat_number', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(default='EE', max_length=2)),
                ('timezone', models.CharField(default='Europe/Tallinn', max_length=64)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
    ]
