# Generated by Django 5.2.15 on 2026-06-28 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_currency', models.CharField(default='EUR', max_length=3)),
                ('default_timezone', models.CharField(default='Europe/Tallinn', max_length=64)),
                ('language', models.CharField(default='et', max_length=16)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=32)),
                ('number_format', models.CharField(default='1 234,56', max_length=32)),
                ('auto_approval_enabled', models.BooleanField(default=False)),
                ('auto_approval_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='core.organization')),
            ],
            options={
                'ordering': ['organization__name', 'id'],
            },
        ),
    ]
